// Datos para el formulario de postulación a Buses Madrid

export const regionesChile = [
  "Arica y Parinacota",
  "Tarapacá",
  "Antofagasta",
  "Atacama",
  "Coquimbo",
  "Valparaíso",
  "Metropolitana de Santiago",
  "Libertador General Bernardo O'Higgins",
  "Maule",
  "Ñuble",
  "Biobío",
  "Araucanía",
  "Los Ríos",
  "Los Lagos",
  "Aysén del General Carlos Ibáñez del Campo",
  "Magallanes y de la Antártica Chilena",
] as const;

export const comunasPorRegion: Record<string, readonly string[]> = {
  "Arica y Parinacota": ["Arica", "Camarones", "Putre", "General Lagos"],
  Tarapacá: ["Iquique", "Alto Hospicio", "Camiña", "Colchane", "Huara", "Pica", "Pozo Almonte"],
  Antofagasta: [
    "Antofagasta",
    "Mejillones",
    "Sierra Gorda",
    "Taltal",
    "Calama",
    "Chiu Chiu",
    "Ollagüe",
    "San Pedro de Atacama",
    "Tocopilla",
  ],
  Atacama: [
    "Copiapó",
    "Caldera",
    "Tierra Amarilla",
    "Chañaral",
    "Diego de Almagro",
    "Vallenar",
    "Alto del Carmen",
    "Freirina",
    "Huasco",
  ],
  Coquimbo: [
    "La Serena",
    "Coquimbo",
    "La Higuera",
    "Paiguano",
    "Andacollo",
    "Ovalle",
    "Combarbalá",
    "Monte Patria",
    "Punitaqui",
    "Illapel",
    "Canela",
    "Los Vilos",
  ],
  Valparaíso: [
    "Valparaíso",
    "Viña del Mar",
    "Concón",
    "Quintero",
    "San Antonio",
    "Santo Domingo",
    "Algarrobo",
    "Cartagena",
    "El Quisco",
    "El Tabo",
    "Limache",
    "Nogales",
    "Olmué",
    "Quilpué",
    "Villa Alemana",
    "Calera",
    "Cabildo",
    "Hijuelas",
    "La Calera",
    "Petorca",
    "Zapallar",
    "Papudo",
    "Quillota",
    "La Cruz",
  ],
  "Metropolitana de Santiago": [
    "Santiago",
    "Puente Alto",
    "Maipú",
    "La Florida",
    "Ñuñoa",
    "La Reina",
    "Providencia",
    "Las Condes",
    "Vitacura",
    "Lo Barnechea",
    "Colina",
    "Lampa",
    "Tiltil",
    "San Bernardo",
    "Buin",
    "Paine",
    "Calera de Tango",
    "Pirque",
    "San José de Maipo",
    "Peñalolén",
    "La Pintana",
    "San Ramón",
    "La Granja",
    "El Bosque",
    "Pedro Aguirre Cerda",
    "Macul",
    "Estación Central",
    "Cerrillos",
    "Mapocho",
    "Pudahuel",
  ],
  "Libertador General Bernardo O'Higgins": [
    "Rancagua",
    "Machalí",
    "Codegua",
    "Donihue",
    "Graneros",
    "Requínoa",
    "San Vicente de Tagua Tagua",
    "Peumo",
    "Pichidegua",
    "San Fernando",
    "Chépica",
    "Chimbarongo",
    "Lolol",
    "Marchihue",
    "Nancagua",
    "Palmilla",
    "Peralillo",
    "Santa Cruz",
    "Pumanque",
    "Litueche",
    "Navidad",
    "Paredones",
    "Pichilemu",
  ],
  Maule: [
    "Talca",
    "Macleans",
    "San Clemente",
    "Pencahue",
    "Pelarco",
    "Río Claro",
    "San Rafael",
    "Curicó",
    "Hualañé",
    "Licantén",
    "Molina",
    "Rauco",
    "Romeral",
    "Sagrada Familia",
    "Teno",
    "Vichuquén",
    "Cauquenes",
    "Chanco",
    "Pelluhue",
    "Constitución",
  ],
  Ñuble: [
    "Chillán",
    "Chillán Viejo",
    "Bulnes",
    "Cobquecura",
    "Coelemu",
    "Ninhue",
    "Pemuco",
    "Pinto",
    "Quirihue",
    "Ránquil",
    "Treguaco",
    "San Nicolás",
    "San Fabián",
    "El Carmen",
    "Yungay",
  ],
  Biobío: [
    "Concepción",
    "Talcahuano",
    "Huachipato",
    "Penco",
    "Tomé",
    "Lota",
    "Arauco",
    "Lebu",
    "Cañete",
    "Los Ángeles",
    "Antuco",
    "Laja",
    "Nacimiento",
    "Negrete",
    "Resguardo",
    "Santa Bárbara",
    "Mulchén",
    "Quilaco",
    "Quilleco",
    "Yumbel",
  ],
  Araucanía: [
    "Temuco",
    "Padre Las Casas",
    "Labranza",
    "Nueva Imperial",
    "Carahue",
    "Cholchol",
    "Cunco",
    "Curarrehue",
    "Freire",
    "Gorbea",
    "Loncoche",
    "Lumaco",
    "Perkinenco",
    "Pitrufquén",
    "Pucón",
    "Puente Pío Pico",
    "Puerto Saavedra",
    "Quepe",
    "Saavedra",
    "Toltén",
    "Traiguén",
    "Vilcún",
    "Villarrica",
    "Victoria",
    "Icalma",
  ],
  "Los Ríos": [
    "Valdivia",
    "Corral",
    "Lachón",
    "Máfil",
    "Mariquina",
    "Panguipulli",
    "Pucón",
    "La Unión",
    "Futrono",
    "Lago Ranco",
    "Río Bueno",
  ],
  "Los Lagos": [
    "Puerto Montt",
    "Puerto Varas",
    "Llanquihue",
    "Los Muermos",
    "Maullín",
    "Dalcahue",
    "Castro",
    "Achao",
    "Quellón",
    "Purranque",
    "Puyehue",
    "Río Negro",
    "Frutillar",
    "Osorno",
    "Purranque",
    "San Pablo",
    "Chonchi",
  ],
  "Aysén del General Carlos Ibáñez del Campo": [
    "Coyhaique",
    "Lago General Carrera",
    "Chile Chico",
    "Aysén",
    "Cisnes",
    "Guaitecas",
  ],
  "Magallanes y de la Antártica Chilena": [
    "Punta Arenas",
    "Puerto Natales",
    "Río Verde",
    "Laguna Blanca",
  ],
};

export const cargosDisponibles = [
  { value: "conductor", label: "Conductor(a)" },
  { value: "mecanico", label: "Mecánico(a) - Mantención" },
  { value: "asistente_bus", label: "Asistente de Bus" },
  { value: "asistente_aseo", label: "Asistente de Aseo" },
  { value: "administrador", label: "Administrador(a) de Contrato" },
  { value: "supervisor", label: "Supervisor(a) de Contrato" },
  { value: "administrativo", label: "Administrativo(a)-Analista- Especialista" },
  { value: "gestion_personas", label: "Gestión Personas" },
  { value: "jefe_area", label: "Jefe(a), Subgerentes y Gerentes de Área" },
  { value: "ingeniero", label: "Ingeniero(a), Encargado(a) o Profesionales" },
  { value: "hsec", label: "HSEC" },
  { value: "alumno", label: "Alumno(as) en práctica" },
] as const;

export const experienciaOpciones = [
  { value: "1-5", label: "1-5 años" },
  { value: "5-10", label: "5-10 años" },
  { value: "10-15", label: "10-15 años" },
  { value: "15-20", label: "15-20 años" },
  { value: "20+", label: "20+ años" },
] as const;

export const licenciaOpciones = [
  { value: "a1_a3", label: "A1 o A3" },
  { value: "a2", label: "A2" },
] as const;

export const disponibilidadOpciones = [
  { value: "misma_comuna", label: "Dentro de su comuna de residencia" },
  { value: "comuna_region", label: "Dentro de su comuna o región" },
  { value: "region_pais", label: "Dentro y fuera de su región" },
  { value: "flexible", label: "Todas las anteriores" },
] as const;
